# Prepare iOS cloud testing from Windows (no Mac required).
# 1) Exposes your local backends via ngrok (or LAN IP for physical iPhone)
# 2) Writes dev-endpoints.ts for the mobile app
# 3) Prints exact EAS + Appetize steps for iPhone 13 simulator in the browser
Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$Root = Split-Path $PSScriptRoot -Parent
$MobileDir = Join-Path $Root "packages\mobile"
$EndpointsFile = Join-Path $MobileDir "src\dev-endpoints.ts"

function Get-LanIP {
    $ip = Get-NetIPAddress -AddressFamily IPv4 |
        Where-Object {
            $_.IPAddress -notlike "127.*" -and
            $_.IPAddress -notlike "169.254.*" -and
            $_.PrefixOrigin -ne "WellKnown"
        } |
        Select-Object -First 1 -ExpandProperty IPAddress
    return $ip
}

function Write-EndpointsFile(
    [string]$AuthUrl,
    [string]$AiUrl,
    [string]$MeshUrl,
    [string]$MeshWsUrl,
    [string]$CouchUrl
) {
    $content = @"
/**
 * API endpoints for mobile dev builds.
 * AUTO-GENERATED by scripts/prepare-ios-cloud-test.ps1 — do not edit by hand.
 * Rebuild the iOS app after changing these values.
 */
export const devEndpoints = {
  authUrl: '$AuthUrl',
  aiUrl: '$AiUrl',
  meshUrl: '$MeshUrl',
  meshWsUrl: '$MeshWsUrl',
  couchdbSyncUrl: '$CouchUrl',
} as const;
"@
    Set-Content -Path $EndpointsFile -Value $content -Encoding UTF8
    Write-Host "Wrote $EndpointsFile" -ForegroundColor Green
}

Write-Host ""
Write-Host "=== Akshar iOS testing from Windows ===" -ForegroundColor Yellow
Write-Host ""

$mode = $args[0]
if (-not $mode) { $mode = "lan" }

if ($mode -eq "lan") {
    $ip = Get-LanIP
    if (-not $ip) { throw "Could not detect LAN IP. Connect to Wi-Fi and retry." }
    Write-Host "Mode: Physical iPhone on same Wi-Fi (best for liveness / real camera)" -ForegroundColor Cyan
    Write-Host "Using LAN IP: $ip"
    Write-EndpointsFile `
        "http://${ip}:8001" `
        "http://${ip}:8002" `
        "http://${ip}:8003" `
        "ws://${ip}:8003" `
        "http://${ip}:5984/akshar_vault"
}
elseif ($mode -eq "ngrok") {
    if (-not (Get-Command ngrok -ErrorAction SilentlyContinue)) {
        throw @"
ngrok is not installed.

Install:
  winget install ngrok.ngrok
Then sign up at https://ngrok.com and run:
  ngrok config add-authtoken YOUR_TOKEN

Restart this script with: .\scripts\prepare-ios-cloud-test.ps1 ngrok
"@
    }
    Write-Host "Mode: Cloud iOS simulator (Appetize) — needs public URLs" -ForegroundColor Cyan
    Write-Host "Starting 3 ngrok tunnels (new windows)..."
    Start-Process ngrok -ArgumentList @("http", "8001", "--log=stdout") | Out-Null
    Start-Sleep -Seconds 2
    Start-Process ngrok -ArgumentList @("http", "8002", "--log=stdout") | Out-Null
    Start-Sleep -Seconds 2
    Start-Process ngrok -ArgumentList @("http", "8003", "--log=stdout") | Out-Null
    Start-Sleep -Seconds 3

    Write-Host ""
    Write-Host "Open http://127.0.0.1:4040 in your browser (ngrok dashboard)." -ForegroundColor Yellow
    Write-Host "Copy the https://....ngrok-free.app URL for each tunnel (8001, 8002, 8003)."
    $auth = Read-Host "Paste AUTH ngrok URL (port 8001)"
    $ai = Read-Host "Paste AI ngrok URL (port 8002)"
    $mesh = Read-Host "Paste MESH ngrok URL (port 8003)"
    $meshWs = $mesh -replace '^https:', 'wss:' -replace '^http:', 'ws:'
    Write-EndpointsFile $auth $ai $mesh $meshWs "$mesh/akshar_vault"
}
else {
    throw "Usage: .\scripts\prepare-ios-cloud-test.ps1 [lan|ngrok]"
}

Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Start backends:  .\start-demo.ps1"
Write-Host "  2. Install EAS CLI: npm install -g eas-cli"
Write-Host "  3. Login (free):    eas login"
Write-Host "  4. Build iOS sim:   cd packages\mobile"
Write-Host "                      eas build --platform ios --profile ios-simulator"
Write-Host "  5. When build finishes, download the .tar.gz artifact from the Expo link."
Write-Host "  6. Extract it — inside is AksharMobile.app"
Write-Host "  7. Go to https://appetize.io — upload the .app, pick iPhone 13, Run."
Write-Host ""
Write-Host "Liveness / camera notes:" -ForegroundColor Yellow
Write-Host "  - Cloud simulator (Appetize): good for UI, loading, navigation. Camera may be limited."
Write-Host "  - Physical iPhone (same Wi-Fi): best for real liveness. Use 'lan' mode above + device build:"
Write-Host "      eas build --platform ios --profile ios-device-dev"
Write-Host "    (requires Apple Developer account, `$99/yr, to install on your phone)"
Write-Host ""
